workspace = name:shell, monitor:eDP-1, default:true
workspace = name:mon, monitor:eDP-1
workspace = name:term, monitor:eDP-1
workspace = name:web, monitor:HDMI-A-1, default:true
workspace = name:chat, monitor:HDMI-A-1
workspace = name:AI, monitor:HDMI-A-1
workspace = name:kaggle, monitor:HDMI-A-1
