# Rule
Rule=azik
# Punctuation Style
PunctuationStyle=Japanese
# Initial Input Mode
InitialInputMode=Hiragana
# Page size
PageSize=7
# Candidate Layout
Candidate Layout=Vertical
# Return-key does not insert new line on commit
EggLikeNewLine=True
# Show Annotation
ShowAnnotation=True
# Candidate Key
CandidateChooseKey="Digit (0,1,2,...)"
# Number candidate of Triggers To Show Candidate Window
NTriggersToShowCandWin=4

[CandidatesPageUpKey]
0=Page_Up

[CandidatesPageDownKey]
0=Next

[CursorUp]
0=Up

[CursorDown]
0=Down

[Dictionaries]
0$type=file
0$file=/home/yoshimi/.config/fcitx5/skk/user.dict
0$mode=ReadWrite
1$type=server
1$host=127.0.0.1
1$port=1178
2$type=file
2$file=/usr/share/skk/SKK-JISYO.L
2$mode=Readonly
3$type=file
3$file=/home/yoshimi/.config/fcitx5/skk/SKK-JISYO.emoji.utf8
3$mode=Readonly

